# Generated by Django 5.2.14 on 2026-05-28 05:42

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaircutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Suba imágenes en formato JPG, PNG o WEBP. Máximo 2MB.', upload_to=gallery.models.upload_to_unique_filename, validators=[gallery.models.validate_image_file])),
                ('alt_text', models.CharField(blank=True, help_text='Descripción del corte para SEO y accesibilidad (ej: Corte Caniche cachorro).', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
