# Generated by Django 5.2.14 on 2026-06-06 07:33

from django.db import migrations

def seed_images(apps, schema_editor):
    HaircutImage = apps.get_model('gallery', 'HaircutImage')
    if not HaircutImage.objects.exists():
        default_images = [
            ("gallery/2fb409c548e34cb7a3f875e20ea37565.png", "Corte caniche prolijo esponjoso"),
            ("gallery/3789e5f6dc764feba73a7b19f2a2e97b.png", "Corte carita redonda tierno"),
            ("gallery/6195bddf34744e5abd4c035a43eb27dd.png", "Corte schnauzer de exposición"),
            ("gallery/c5688a9bc1a148b08156859428e2742c.png", "Corte higiénico y patitas limpias"),
            ("gallery/c7802b434e3145368af0961350bbada1.png", "Corte de pelo moderno pomerania"),
        ]
        for path, alt in default_images:
            HaircutImage.objects.create(image=path, alt_text=alt)

def remove_images(apps, schema_editor):
    HaircutImage = apps.get_model('gallery', 'HaircutImage')
    HaircutImage.objects.filter(image__startswith='gallery/').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_images, remove_images),
    ]
